# Generated by Django 4.2 on 2024-04-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartorder_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='cart_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
